### ISSUE TITLE
list 何番目かを指定し、その番号の場所のlist表示する

### ISSUE THREAD

**Issue by kojake** [kojake/happybrithdayapp#6]

**Comment by kojake** [comment]
高津先生
お休み中の中失礼します。

今新しいアプリを作っているのですが、そこで教えて欲しいことがあります。
listがあり、listには0,1,2みたいに番号があるじゃないですか、listの中の番号を指定し、
その番号の文字列を表示したいのですがどうすれば良いでしょうか？

海斗より

**Comment by kojake** [comment]
調べたら、出てきたので大丈夫です

**Comment by yuuki00682200** [comment]
よかったです、indexについて理解できるとList周りはすぐに使いこなせるようになりますね
